name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  cachix:
    name: Build Packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
        - wine-osu
        - wine-ge
        - wine-tkg
        - proton-ge
        - faf-client
        - faf-client-unstable
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: cachix/install-nix-action@v20
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: nix-gaming
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build -L .#${{ matrix.package }}
