name: Update

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  cachix:
    name: Update sources
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - nix run nixpkgs#npins update
          - pkgs/osu-lazer-bin/update.sh
          - pkgs/osu-stable/update.sh
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: cachix/install-nix-action@v17
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
      - run: ${{ matrix.command }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[gha] bump npins inputs"
