name: Update packages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # daily

jobs:
  update:
    if: github.repository == 'fufexan/nix-gaming'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: cachix/cachix-action@v15
        with:
          name: nix-gaming
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: |
          nix run .#npins update
          pkgs/cnc-ddraw/update.sh
          pkgs/dxvk/update.sh
          pkgs/faf-client/update.sh
          pkgs/faf-client/update-src.sh
          pkgs/osu-lazer-bin/update.sh
          pkgs/osu-stable/update.sh
          pkgs/proton-osu-bin/update.sh
          pkgs/technic-launcher/update.sh
          pkgs/wine/update-wine-cachyos.sh
          pkgs/wine/update-wine-ge.sh
          pkgs/wine/update-wine-tkg.sh
          pkgs/star-citizen/update.sh

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update packages"
          push_options: '--force'

  build:
    needs: update
    uses: ./.github/workflows/build.yml
    secrets: inherit
